name: "Campfire"
description: "Basecamp's Once Campfire chat application for teams"
version: "1.0.1"
slug: "campfire"
init: false
arch:
  - aarch64
  - amd64
startup: application
boot: manual
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Campfire web interface"
webui: "http://[HOST]:[PORT:3000]"
ingress: true
ingress_port: 3000
panel_icon: mdi:campfire
map:
  - "share:rw"
options:
  domain: ""
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  admin_password: ""
  secret_key_base: ""
  database_url: ""
schema:
  domain: str
  ssl: bool
  certfile: str
  keyfile: str  
  admin_password: password
  secret_key_base: password
  database_url: str?
image: "ghcr.io/kebabmane/{arch}-addon-campfire"